### PR TITLE
[R-package] changes to support read/write performance in CMake builds

### PR DESCRIPTION
**Pull request by jameslamb**
Opening this PR to aid in the discussion on https://github.com/microsoft/LightGBM/pull/3405, about whether bringing dependencies `fmt` and `fast_double_parser` into `LightGBM` will cause issues for getting `{lightgbm}` (`LightGBM`'s R package) onto CRAN.

With the changes below, it's possible to build a `{lightgbm}` that passes almost all tests.

**CMake-based installation**

```shell
git submodule --init --recursive
Rscript build_r.R
R CMD check lightgbm_*.tar.gz --as-cran
```

**CRAN installation with `configure` created by `Autoconf`**

```shell
git submodule --init --recursive
sh build-cran-package.sh
R CMD check lightgbm_*.tar.gz --as-cran
```

## `R CMD check` results

The **CMake-based installation** did not have any issues on my Mac.

The **CRAN installation** has this NOTE that would prevent the R package from getting to CRAN:

```text
* checking compiled code ... NOTE
File ‘lightgbm/libs/lightgbm.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
    Object: ‘external_libs/fmt/format.o’
  Found ‘___stdoutp’, possibly from ‘stdout’ (C)
    Object: ‘external_libs/fmt/format.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
```

For a lot of background on this issue, see https://github.com/microsoft/LightGBM/pull/2901.

## Notes for reviewers

Let's talk about this on https://github.com/microsoft/LightGBM/pull/3405 instead of here, to avoid splitting the conversation.

### CODE REVIEW

**Comment by AlbertoEAF** [comment]
Had to rebase+squash manually. Merged to my MR through a fast-forward. Don't know why it didn't detect the rebase&squash&merge.

**Comment by AlbertoEAF** [comment]
@jameslamb given that you're adding more changes to master in other PR's related to the same issue, now I'm not sure I was supposed to have merged this to my MR, can you confirm?

Thank you

**Comment by jameslamb** [comment]
> given that you're adding more changes to master in other PRs related to the same issue

@AlbertoEAF what does this refer to? Can you give me an example?

> now I'm not sure I was supposed to have merged this to my MR, can you confirm?

It's fine that you merged it, we can move all of the discussion back to https://github.com/microsoft/LightGBM/pull/3405 now.

**Comment by AlbertoEAF** [comment]
Great ;)

> @AlbertoEAF what does this refer to? Can you give me an example?

I was talking of the other PR's you have mentioned in the main PR https://github.com/microsoft/LightGBM/pull/3405:
- https://github.com/microsoft/LightGBM/pull/3435
- https://github.com/microsoft/LightGBM/pull/3434

**Comment by jameslamb** [comment]
Oh I see. I wouldn't call those "related to the same issue" and they don't conflict with the ongoing work in https://github.com/microsoft/LightGBM/pull/3405

**Pull request closed without merging**
